<div class="header nonselectable">
    <div class="logo"></div>
    <div class="tools">
        <div class="type">
            <div id="usericon" title="Profile"></div>
            <div id="usertype" class="caption">Super admin</div>
        </div>
        <div id="opcsicon" class="hand" title="Options"></div>
        <a href="<?php echo $this->baseUrl();?>/admin/index/logout" >
            <div id="logouticon" class="hand" title="Logout"></div>
        </a>
    </div>
</div>