<div class="menubox nonselectable">
    <div class="bg">
        <div class="gradient">
            <div id="menu">
                <div class="item hand">
                    <a href="<?php echo $this->baseUrl();?>/admin/home" >
                        <span class="caption">Home</span>
                    </a>
                </div>
                <div class="item hand">
                    <a href="<?php echo $this->baseUrl();?>/admin/cities" >
                        <span class="caption">Cities</span>
                    </a>
                </div>
                <div class="item hand">
                    <a href="<?php echo $this->baseUrl();?>/admin/business" >
                        <span class="caption">Business</span>
                    </a>
                </div>
                <div class="item hand">
                    <a href="<?php echo $this->baseUrl();?>/admin/users" >
                        <span class="caption">Users</span>
                    </a>
                </div>
                <div class="item hand">
                    <a href="<?php echo $this->baseUrl();?>/admin/orders" >
                        <span class="caption">Orders</span>
                    </a>
                </div>
                <div class="item hand">
                    <a href="<?php echo $this->baseUrl();?>/admin/statistics" >
                        <span class="caption">Statistics</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>