<div id="main">
    <div id="secondarymenu">
        <div class="boxbutton nonselectable hand" onclick="window.location='/admin/cities'">
            <div class="img business"></div>
            <div class="caption1">CITIES</div>
            <div class="caption2">my cities list</div>
        </div>
        <div class="boxbutton nonselectable hand" onclick="window.location='/admin/business'">
            <div class="img business"></div>
            <div class="caption1">BUSINESS</div>
            <div class="caption2">business list</div>
        </div>
        <div class="boxbutton nonselectable hand" onclick="window.location='/admin/orders'">
            <div class="img orders"></div>
            <div class="caption1">ORDERS</div>
            <div class="caption2">orders list</div>
        </div>
        <div class="boxbutton nonselectable hand" onclick="window.location='/admin/users'">
            <div class="img users"></div>
            <div class="caption1">USERS</div>
            <div class="caption2">active users</div>
        </div>
        <div class="boxbutton nonselectable hand" onclick="window.location='/admin/statistics'">
            <div class="img statistics"></div>
            <div class="caption1">STATISTICS</div>
            <div class="caption2">data analysis</div>
        </div>
    </div>
</div>