<!doctype html>
<head>
	
	<?php echo $this->headTitle() ?> 
    <?php echo $this->headMeta() ?>

	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

	<meta name="keywords" content="givenchy" />	
	<meta name="description" content="GIVENCHY THE CLUB" />
	<meta name="robots" content="noindex, nofollow" />
    
	<?php 
		$this->headLink()
            ->prependStylesheet($this->baseUrl().'/css/flexslider.css')
            ->prependStylesheet($this->baseUrl().'/css/estilo.css');

		$this->headScript()
            ->prependFile($this->baseUrl().'/js/custom.js')
            ->prependFile($this->baseUrl().'/js/jquery.flexslider-min.js')
            ->prependFile($this->baseUrl().'/js/jquery.min.js');

        echo $this->headLink();
        echo $this->headScript();                               
    ?>

    <script type="text/javascript">
    	var baseUrl = '<?= json_encode($this->baseUrl()); ?>';
    </script>
<style>
hr{width:90%;color:#000;border:1px solid #000;border-left:none;border-right:none;border-bottom:none;}
.capa_sombra{position:fixed;left:0;top:0;background-color:#000;opacity:0.6;filter:alpha(opacity=60);z-index:1000;display:none;}
.capa_ventana{position:fixed; font-family:arial;font-size:1em;border:0.05em solid black;overflow:auto;background-color:#fff;z-index:1001;display:none;}
</style>
</head>

<body>
        KKKKKKKKKKKKKKKKKKKKKKKKK
<div id="capa_sombra" class="capa_sombra"></div>
<div id="capa_ventana" class="capa_ventana">
    <table width="100%">
        <tr>
            <td width="20"><a href="#"><img src="/images/x.png" onClick="closeModal();" border="0" /></a></td>
        </tr>
    </table>

</div>
<div style="height:40px;" >
</div>
    <div id="info" >
    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="center"><img src="/images/fondo_logo.jpg"  /></td>
        </tr>
        <tr>
            <td><br /><br />
			<!-- Menu -->
			<?php echo $this->partial('menu.phtml', array('current_page' => $this->current_page, 'user' => $this->user, 'page_title' => $this->page_title));?>
		    </td>
        </tr>
		
        <?php echo $this->layout()->content ?>	
        </table>
     </div>
     <div style="height:40px; padding:0 0 20px 0" >
     <div id="footer">
        <div class="copyright"><?php echo date("Y") ?> &copy; GIVENCHY ESPA&Ntilde;A</div>
        <div class="footer-menu">
            <a href="javascript:openModal('contacto.html');" class="link">Contacte con nosotros</a>&nbsp;&nbsp;<a href="javascript:openModal('condiciones.html');" class="link">Condiciones de uso</a>
        </div>
     </div>                                      
</div>
<BR /><BR />
</body>
</html>
