<tr><td colspan="7">&nbsp;</td></tr>
    <?php foreach ( $this->centroList as $centro ): ?>
            <tr>
                <td><?=$centro->cod?></td>
                <td class="nombre"><?=$centro->centro?></td>
                <td class="apellido"><?=$centro->direccion?></td>
                <td class="ciudad" align="center"><?=$centro->ciudad?></td>
                <td class="idcentro" align="center"><?=$centro->cp?></td>
                <td class="ver" colspan="2" align="center"><input type="button" id="button" value="VER" class="button btn-edit" onClick="openModal(<?=$centro->idcentro?>); " /></td>
               </tr>
             <tr><td colspan="5"><hr /></td></tr>
    <?php endforeach; ?>
<tr><td colspan="6">
<br />
<center>
<?php if($this->curPage > 1): ?>
<font class="showpageNum">
    <a href="/admin/centros?page=<?=($this->curPage-1)?>" class="btn-page-arrow btn-prev-page">            
        ANTERIOR
    </a>
</font>&nbsp;&nbsp;&nbsp;
<?php endif; ?>
<?php for($n=1; $n<$this->pageCount+1; $n++): ?>
    <?php if($n != $this->curPage): ?>
        <font class="showpageNum"><a href="/admin/centros?page=<?=$n?>" ><?=$n?></a></font>&nbsp;
    <?php else: ?>
        <font class="showpagePoint"><?=$n?></font>&nbsp;
    <?php endif; ?>
<?php endfor; ?>
<?php if ( $this->curPage < $this->pageCount ): ?>
&nbsp;&nbsp;&nbsp;<font class="showpageNum">
    <a href="/admin/centros?page=<?=($this->curPage+1)?>" class="btn-page-arrow btn-next-page"> SIGUIENTE</a>
</font>
<?php endif; ?>
</center>
</td></tr>